### ISSUE TITLE
Generator 问题整理

### ISSUE THREAD

**Issue by Shigma** [Symbolk/Code2Graph#17]
## XML

- xml 的 file 在 windows 下面都是 \\，java 是 /，以及文件节点 xml 的 identifier layer 是 null 而 java 是空串（我也不清楚哪边是更好的）

## Java

- 部分类型目前尚不支持
  - implements
  - annotation
  - 函数参数

**Comment by Symbolk** [comment]
可以再详细点吗？
1. implements应该是支持的，只不过边的名字是extended_interface（extends对应边的名字叫super_class）。
例如，对于gen.java/test/resources/TestMethod.java中，生成的图是包含extends和implements的：

![image](https://user-images.githubusercontent.com/14107297/131435694-0089b2b6-0d96-4f84-9267-cb844ff2d82f.png)

2.

**Comment by Symbolk** [comment]
2. annotation和 3. 函数参数主要是指未生成对应节点以及边吗？

**Comment by Symbolk** [comment]
- [ ] 关于各处path的统一
- [ ] Annotation已支持 (定义和使用)
- [ ] MethodInvocation argument支持
- [ ] implements和extends在unresolved情况下无节点生成的问题修复（如何避免过多not-from-source节点？）

**Comment by Symbolk** [comment]
目前top level type declaration直接作为cuNode的child，是否需要对package declaration也新建节点？

**Comment by Symbolk** [comment]
是否需要对package declaration新建节点？
