### ISSUE TITLE
feat: Extractor执行代码上传；导出文件名改为repoName:commitID

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/Code2Graph#37]
1. 执行generateInstances()的代码上传，以便其他人可以在本地抽取GT
2. 在GitService中添加获取repo HEAD commit id的接口，git rev-parse --short HEAD
3. GT和output导出文件名格式都改为：repoName:commitID
4. 在Evaluation中寻找gtPath和otPath需要特殊处理一下

因为发现前一次结果较差原因是我本地的repo与GT所在的commit不一致所致，最新结果：

NewPie:ba6fdecba
![image](https://user-images.githubusercontent.com/14107297/134641271-e549c62c-1e1a-4267-a9ef-d238878559c7.png)

VirtualXposed:9c20336a
![image](https://user-images.githubusercontent.com/14107297/134648477-05b46c41-d326-49a0-94d3-500c1c09f353.png)

GSYVideoPlayer:e3eae615
![image](https://user-images.githubusercontent.com/14107297/134647109-3c7c8379-bb9a-430d-b410-cb97350feee3.png)

**Comment by TsukimiRini** [comment]
第4条在Evaluation中寻找gtPath和otPath需要特殊处理一下具体是指？

**Comment by Symbolk** [comment]
> 第4条在Evaluation中寻找gtPath和otPath需要特殊处理一下具体是指？

是在evaluation中的这里：

![image](https://user-images.githubusercontent.com/14107297/134667693-d8ce592f-745d-4361-99bb-eeed88b5dc40.png)

可以看到，加入了commitid之后文件名就不是reponame.csv了，而是需要修改一下处理。
比如说先读取出所有resources下的文件路径，再确定具体的文件名。
